import type {Metadata} from 'next';
import Image from 'next/image';
import {ArrowUpRight,MapPin,Clock3,Users,Check,Monitor} from 'lucide-react';
import Footer from '@/components/Footer';
import TrustStrip from '@/components/brand/TrustStrip';
import {FaqSection,PreAuditCTA,TextLink} from '@/components/brand/Sections';
import {formationCities,trainingFaq,type LocalTraining} from '@/lib/formation-cities';
import {cityLocation} from '@/lib/cities-content';
import b from '@/components/brand/Brand.module.css';
import s from './FormationCities.module.css';
export function trainingMetadata(slug:string):Metadata {const d=formationCities.find(x=>x.city.slug===slug)!;const title=`Formation IA ${cityLocation(d.city)} : équipes et dirigeants`;return {title,description:d.intro,alternates:{canonical:`https://althoce.com/formation-ia-${slug}/`},openGraph:{title,description:d.intro,url:`https://althoce.com/formation-ia-${slug}/`,images:[{url:`/images/cities/${slug}.webp`,alt:d.city.landmark}]},twitter:{card:'summary_large_image',title,description:d.intro,images:[`/images/cities/${slug}.webp`]}}}
const programs=[{slug:'ia-fondamentaux',title:'IA Fondamentaux',note:'Débuter avec méthode',duration:'1 journée · 7 h',text:'Comprendre les outils, formuler une demande et vérifier les réponses sur des cas du quotidien.'},{slug:'ia-avancee',title:'IA Avancée',note:'Approfondir la pratique',duration:'1 journée · 7 h',text:'Structurer vos usages et construire un premier agent dans un atelier guidé.'},{slug:'coaching-dirigeant',title:'Coaching IA Dirigeant',note:'Avancer en individuel',duration:'4 séances · 1 h 30',text:'Travailler sur vos priorités et votre feuille de route avec un accompagnement personnel.'}];
export function TrainingCityLinks(){return <section className={s.directory} aria-labelledby="formation-villes-title"><div className={b.container}><h2 id="formation-villes-title">Former vos équipes,<br/>partout en France.</h2><p>Des ateliers sur site ou à distance, selon les modalités convenues avec votre entreprise.</p><nav aria-label="Formations IA par ville">{formationCities.map(d=><a key={d.city.slug} href={`/formation-ia-${d.city.slug}/`}>{d.city.name}<ArrowUpRight size={15} aria-hidden="true"/></a>)}</nav></div></section>}
function Schema({d}:{d:LocalTraining}){const url=`https://althoce.com/formation-ia-${d.city.slug}/`;return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'Service',name:`Formation IA ${cityLocation(d.city)}`,url,description:d.intro,provider:{'@type':'Organization',name:'Althoce','@id':'https://althoce.com/#organization'},areaServed:{'@type':'City',name:d.city.name}},{'@type':'BreadcrumbList',itemListElement:[['Accueil','https://althoce.com/'],['Formations IA','https://althoce.com/services/formation-ia/'],[d.city.name,url]].map(([name,item],i)=>({'@type':'ListItem',position:i+1,name,item}))},{'@type':'FAQPage',mainEntity:trainingFaq(d).map(x=>({'@type':'Question',name:x.q,acceptedAnswer:{'@type':'Answer',text:x.a}}))}]}).replace(/</g,'\\u003c')}}/>}
export default function FormationCityPage({slug}:{slug:string}){const d=formationCities.find(x=>x.city.slug===slug)!;const place=cityLocation(d.city);return <><Schema d={d}/><main className={b.page}>
<section className={s.hero}><div className={b.container}><nav className={b.breadcrumb} aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span><a href="/services/formation-ia/">Formations IA</a><span>/</span><span aria-current="page">{d.city.name}</span></nav><div className={s.heroGrid}><div><h1>Formation IA {place}.<br/><span>Sur mesure pour<br/>vos collaborateurs.</span></h1><p className={b.lead}>Des formations IA sur mesure, adaptées aux outils, au niveau et au quotidien de vos collaborateurs. {d.intro}</p><a className={b.primary} href="#parcours">Trouver votre parcours<ArrowUpRight size={18} aria-hidden="true"/></a><p className={s.location}><MapPin size={16} aria-hidden="true"/>{d.city.region}</p></div><div className={s.landmark}><Image src={`/images/cities/${slug}.webp`} alt={`${d.city.landmark}, ${d.city.name}.`} fill priority sizes="(max-width:900px) 90vw, 48vw"/><span>{d.city.landmark}</span></div></div></div></section>
<TrustStrip className={b.container}/>
<section className={b.section}><div className={`${b.container} ${s.split}`}><div className={s.photo}><Image src="/images/sectors/finance-formation.webp" alt="Une équipe apprend ensemble autour de ses outils pendant un atelier en bureau." fill sizes="(max-width:900px) 90vw, 48vw"/></div><div><h2>Votre quotidien.<br/><span>Le fil conducteur de la formation.</span></h2><p className={b.lead}>Avant la session, nous échangeons sur vos tâches, vos outils et le niveau des participants. Nous adaptons les exercices à leurs situations de travail, pour que chacun reparte avec des méthodes qu’il peut réutiliser dès le lendemain.</p><ul className={s.facts}><li><Users size={20} aria-hidden="true"/>Jusqu’à 10 participants par session collective</li><li><Monitor size={20} aria-hidden="true"/>Sur site ou à distance, selon le cadrage</li><li><Check size={20} aria-hidden="true"/>Un point de suivi à 30 jours</li></ul></div></div></section>

<section className={`${b.section} ${s.soft}`} id="parcours"><div className={b.container}><div className={s.heading}><h2>Le bon parcours,<br/><span>au bon moment.</span></h2><p>Trois points de départ pour construire votre formation sur mesure. Les ateliers sont adaptés au niveau, aux métiers et aux objectifs des participants.</p></div><div className={s.programs}>{programs.map((p,i)=><a key={p.slug} href={`/services/formation-ia/${p.slug}/`}><span className={s.programNumber}>0{i+1}</span><small>{p.note}</small><h3>{p.title}</h3><p>{p.text}</p><span className={s.duration}><Clock3 size={16} aria-hidden="true"/>{p.duration}</span><strong>Voir le programme<ArrowUpRight size={18} aria-hidden="true"/></strong></a>)}</div></div></section>

<section className={s.funding}><div className={`${b.container} ${s.heading}`}><div><h2>Préparer aussi<br/><span>les conditions de réussite.</span></h2><p className={b.lead}>Disponibilités, équipement, besoins d’accessibilité et financement : nous les abordons avant la formation.</p></div><div><h3>Financement OPCO</h3><p>Une prise en charge peut être étudiée via notre organisme partenaire, sous réserve des conditions de votre financeur. Elle n’est pas automatique.</p><TextLink href="/contact/">Préparer votre demande</TextLink></div></div></section>
<section className={b.section}><div className={b.container}><div className={s.heading}><h2>Un exercice qui ressemble<br/><span>à votre travail.</span></h2><p>{d.audience} : voici un point de départ à adapter aux participants.</p></div><div className={s.exercise}><div><small>En atelier</small><h3>{d.exercise}</h3></div><div><Check size={25} aria-hidden="true"/><small>Ce que vous construisez</small><p>{d.deliverable}</p></div></div><p className={s.note}>Exemple pédagogique, avec des documents autorisés, anonymisés ou fictifs selon le contexte.</p><TextLink href={`/secteurs/${d.sector}/`}>Explorer les usages de ce secteur</TextLink></div></section>
<FaqSection id="faq-formation-locale" title={`Votre formation IA ${place}.`} description="Les réponses pour organiser la session avec votre équipe." items={trainingFaq(d)} showContactLink={false}/><PreAuditCTA title="Faisons le point sur votre équipe." description="En 30 minutes, parlons des participants, de leurs usages et du parcours adapté. Ce premier échange est offert, sans engagement."/>
<section className={s.near}><div className={b.container}><h2>Et autour de {d.city.name} ?</h2><nav aria-label="Autres villes de formation">{d.city.near.map(slug=>{const c=formationCities.find(x=>x.city.slug===slug)!;return <a key={slug} href={`/formation-ia-${slug}/`}>{c.city.name}<ArrowUpRight size={16} aria-hidden="true"/></a>})}</nav><TextLink href={`/agence-ia-${slug}/`}>L’accompagnement Althoce {place}</TextLink></div></section>
</main><Footer showCta={false}/></>}
