import Image from 'next/image';
import { ArrowUpRight, Compass, Users, CheckCheck } from 'lucide-react';
import { caseStories, caseDetails, type CaseStory } from '@/lib/cases-content';
import { PreAuditCTA, TextLink } from '../brand/Sections';
import b from '../brand/Brand.module.css';
import s from './Cases.module.css';

export function CaseCards({stories=caseStories,featured=false}:{stories?:CaseStory[];featured?:boolean}) {return <div className={`${s.cards} ${featured?s.gallery:''}`}>{stories.map((d)=>{const detail=caseDetails[d.metier];return <a href={`/cas-clients/${d.slug}/`} key={d.slug} className={s.card}><div className={s.cardPhoto}><Image src={`/images/services/${detail.image}.webp`} alt={detail.alt} fill sizes="(max-width:600px) 90vw, (max-width:900px) 45vw, 50vw"/><span className={s.cardSector}>{d.sector}</span></div><div className={s.cardBody}><p className={s.cardName}>{d.name}</p><h3>{d.title}</h3><div className={s.cardMetrics}>{detail.highlights.map(x=><div key={x.label}><strong>{x.value}</strong><span>{x.label}</span></div>)}</div><div className={s.cardBottom}><span>Lire l’étude de cas</span><ArrowUpRight size={22} aria-hidden="true"/></div></div></a>})}</div>}
export function CaseResults({story:d}:{story:CaseStory}){const detail=caseDetails[d.metier];return <section className={s.resultsSection} id="resultats" aria-labelledby="resultats-title"><div className={b.container}><div className={s.heading}><div><h2 id="resultats-title">Les résultats.<br/><span>Ce qui a changé.</span></h2><p className={s.period}>{detail.period}.</p></div><p>{detail.takeaway}</p></div><div className={s.resultsGrid}><div className={s.resultSpotlight}><span>Le repère clé</span><strong>{detail.highlights[0].value}</strong><p>{detail.highlights[0].label}</p></div><div className={s.comparisons}><div className={s.comparisonHead}><span>Indicateur</span><span>Avant</span><span>Après</span></div>{detail.results.map(x=><div className={s.comparisonRow} key={x.label}><h3>{x.label}</h3><div><span className={s.mobileLabel}>Avant</span>{x.before}</div><div><span className={s.mobileLabel}>Après</span><strong>{x.after}</strong></div></div>)}</div></div><p className={s.resultNote}>Résultats observés dans le contexte de cette mission, sur le périmètre et la période présentés.</p></div></section>}
export function CaseSchema({story:d}:{story?:CaseStory}) {const url=`https://althoce.com/cas-clients/${d?`${d.slug}/`:''}`;return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':[d?{'@type':'Article','headline':d.title,'description':d.challenge,'url':url,'mainEntityOfPage':url,'author':{'@type':'Organization','name':'Althoce','url':'https://althoce.com/'}}:{'@type':'CollectionPage','name':'Cas clients Althoce','url':url,'mainEntity':{'@type':'ItemList','itemListElement':caseStories.map((x,i)=>({'@type':'ListItem','position':i+1,'name':x.name,'url':`https://althoce.com/cas-clients/${x.slug}/`}))}},{'@type':'BreadcrumbList','itemListElement':[{name:'Accueil',url:'https://althoce.com/'},{name:'Cas clients',url:'https://althoce.com/cas-clients/'},...(d?[{name:d.name,url}]:[])].map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:x.url}))}]})}}/>}
export default function CasePage({story:d}:{story:CaseStory}){const detail=caseDetails[d.metier];return <main className={b.page}>
<section className={s.hero}><div className={b.container}><nav className={b.breadcrumb} aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span><a href="/cas-clients/">Cas clients</a><span>/</span><span aria-current="page">{d.name}</span></nav><div className={s.heroGrid}><div><p className={s.sector}>{d.sector}</p><h1>{d.title}</h1><p className={b.lead}>{d.context}</p><TextLink href="#terrain">Découvrir le point de départ</TextLink></div><div className={s.photo}><Image src={`/images/services/${detail.image}.webp`} alt={detail.alt} fill priority sizes="(max-width:900px) 90vw, 48vw"/><span className={s.photoTag}>L’usage part du quotidien.</span></div></div><div className={s.route}><span><Compass size={19} aria-hidden="true"/> Observer le terrain</span><span><Users size={19} aria-hidden="true"/> Concevoir avec l’équipe</span><span><CheckCheck size={19} aria-hidden="true"/> Garder la main</span></div></div></section>
<section className={b.section} id="terrain"><div className={`${b.container} ${s.editorial}`}><h2>Avant les outils,<br/><span>une réalité de terrain.</span></h2><div><p className={s.largeText}>{d.challenge}</p><p className={s.caption}>Dossier anonymisé · {d.name}</p></div></div></section>
<section className={s.solution}><div className={b.container}><div className={s.editorial}><div><h2>Une réponse conçue<br/>pour ce contexte.</h2><TextLink href={`/agent-ia/${d.metier}/`}>Explorer les usages de ce métier</TextLink></div><p className={s.largeText}>{d.solution}</p></div><ol className={s.steps}>{d.steps.map((text,i)=><li key={text}><span className={s.stepNumber}>0{i+1}</span><h3>{['Comprendre','Construire','Transmettre'][i]}</h3><p>{text}</p></li>)}</ol></div></section>
<CaseResults story={d}/><section className={b.section}><div className={`${b.container} ${s.heroGrid}`}><div className={s.photo}><Image src="/images/services/cas-equipe.webp" alt="Une dirigeante et deux collègues échangent autour d’un bilan de travail" fill sizes="(max-width:900px) 90vw, 48vw"/></div><div><h2>Ce qui compte,<br/><span>au-delà de l’outil.</span></h2><p className={b.lead}>{d.learning}</p><div className={s.human}><Users size={24} aria-hidden="true"/><p>Une solution utile se prend en main. Formation, documentation et suivi font partie de l’accompagnement Althoce.</p></div><TextLink href="/services/formation-ia/">Accompagner vos équipes</TextLink></div></div></section>
<section className={`${b.section} ${s.related}`}><div className={b.container}><div className={s.heading}><h2>D’autres contextes.<br/><span>La même écoute.</span></h2><TextLink href="/cas-clients/">Tous les cas clients</TextLink></div><CaseCards stories={caseStories.filter(x=>x.slug!==d.slug).slice(0,3)}/></div></section><PreAuditCTA/>
</main>}
export function CasesHub(){return <main className={b.page}><section className={s.hero}><div className={b.container}><nav className={b.breadcrumb} aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span><span aria-current="page">Cas clients</span></nav><div className={s.heroGrid}><div><h1>Des équipes.<br/>Des défis concrets.<br/><span>Une IA à leur mesure.</span></h1><p className={b.lead}>Comptabilité, commerce, support, opérations : explorez les contextes qui donnent du sens aux agents IA et à l’automatisation sur mesure.</p><TextLink href="#dossiers">Explorer les cas clients</TextLink></div><div className={s.photo}><Image src="/images/services/cas-equipe.webp" alt="Une équipe échange autour de son travail dans un bureau lumineux" fill priority sizes="(max-width:900px) 90vw, 48vw"/><span className={s.photoTag}>Tout commence par une conversation.</span></div></div></div></section><section className={b.section} id="dossiers"><div className={b.container}><div className={s.heading}><h2>À chaque entreprise,<br/><span>son point de départ.</span></h2><p>Des missions anonymisées, des résultats concrets et les équipes qui les rendent possibles.</p></div><CaseCards featured/></div></section><section className={s.solution}><div className={`${b.container} ${s.editorial}`}><h2>Votre contexte ne rentre<br/>pas dans une case.</h2><div><p className={s.largeText}>Ces usages ouvrent la discussion. Votre solution se construit à partir de vos outils, de vos habitudes et de ce que vous souhaitez changer.</p><TextLink href="/services/audit-ia/">Partir du terrain avec un diagnostic IA</TextLink></div></div></section><PreAuditCTA/></main>}
