import Image from 'next/image';
import Funding from './formation/Funding';
import { ArrowUpRight } from 'lucide-react';
import { Breadcrumb, TextLink, FaqSection, PreAuditCTA } from './brand/Sections';
import TrustStrip from './brand/TrustStrip';
import { fondamentaux, avancee, formationFaq } from '@/lib/formations';
import b from './brand/Brand.module.css';
import s from './formation/Formation.module.css';
export default function FormationIAPageClient() {
 return <main className={b.page}>
  <section className={s.hero}><div className={`${b.container} ${s.grid}`}><div><Breadcrumb label="Formation IA"/><h1>La formation IA.<br/><span>Une compétence qui se partage.</span></h1><p className={b.lead}>Donnez à vos équipes les repères et la confiance pour utiliser l’IA dans leur métier. Deux formations d’une journée pour vos équipes et un coaching individuel pour dirigeants, avec vos outils et vos vrais dossiers.</p><a className={b.primary} href="#formations">Choisir votre parcours<ArrowUpRight size={18} aria-hidden="true"/></a></div><div className={s.photo}><Image src="/images/services/formation.webp" alt="Une formatrice accompagne une petite équipe pendant un atelier dans un bureau." fill priority sizes="(max-width:900px) 90vw, 50vw"/></div></div></section>
  <TrustStrip className={b.container}/>
  <section className={b.section} id="formations"><div className={b.container}><div className={b.sectionHeading}><h2>Un point de départ<br/><span>pour chacun.</span></h2><p>En équipe ou en individuel : choisissez le parcours adapté à votre rôle et à votre pratique.</p></div><div className={s.courses}>{[fondamentaux,avancee].map((f,i)=><article className={s.course} key={f.slug}><span className={s.courseNumber} aria-hidden="true">0{i+1}</span><h3>{f.title}</h3><p>{i===0?'Comprendre les possibilités et les limites de l’IA, structurer ses demandes et pratiquer sur ses tâches quotidiennes.':'Approfondir sa pratique, créer un assistant métier et expérimenter une première automatisation guidée.'}</p><small>{i===0?'Pour commencer, sans prérequis.':'Pour les utilisateurs réguliers de l’IA.'}<br/>1 journée · 7 heures · Jusqu’à 10 participants</small><a href={`/services/formation-ia/${f.slug}/`}>Découvrir le programme<ArrowUpRight size={20} aria-hidden="true"/></a></article>)}<article className={`${s.course} ${s.coaching}`}><div><span className={s.courseNumber} aria-hidden="true">03</span><h3>Coaching IA Dirigeant</h3><p>Un espace pour pratiquer sur vos dossiers, créer votre assistant personnel et tracer la feuille de route IA de votre entreprise.</p></div><div><small>Individuel · Aucun prérequis<br/>4 séances de 1 h 30 · À votre rythme</small><a href="/services/formation-ia/coaching-dirigeant/">Découvrir le coaching<ArrowUpRight size={20} aria-hidden="true"/></a></div></article></div></div></section>
  <section className={`${b.section} ${s.soft}`}><div className={`${b.container} ${s.grid}`}><div className={s.photo}><Image src="/images/home/atelier-equipes.webp" alt="Des collègues travaillent ensemble sur un cas pratique autour d’un carnet et d’un ordinateur." fill sizes="(max-width:900px) 90vw, 50vw"/></div><div><h2>Vos vrais sujets.<br/><span>Vos premiers réflexes.</span></h2><p className={b.lead}>Un document à synthétiser, une réponse à préparer, une information à retrouver : les participants apprennent en faisant, avec l’accompagnement du formateur.</p><ul className={s.checks}><li>Avant : comprendre les attentes et vérifier le niveau.</li><li>Pendant : essayer, comparer et améliorer sur des cas concrets.</li><li>Après : des supports et une visio de suivi à 30 jours.</li></ul></div></div></section>
  <section className={b.section}><div className={`${b.container} ${s.grid}`}><div><h2>Préparée pour vous.<br/><span>Accessible à votre équipe.</span></h2><p className={b.lead}>Les formations collectives se déroulent en présentiel ou distanciel, en intra ou inter-entreprise. Nous préparons les modalités avec vous et étudions les besoins d’aménagement signalés en amont.</p></div><Funding/></div></section>
  <FaqSection id="faq-formations" title="Avant de vous lancer." description="Niveau, outils et organisation : les repères utiles." items={formationFaq}/>
  <PreAuditCTA title="Et si votre équipe passait à la pratique ?" description="Parlons de vos usages et du niveau de vos équipes lors d’un premier échange de 30 minutes offert."/>
 </main>;
}
