import {cityStories,cityLocation,type CityStory} from './cities-content';
export type LocalTraining={city:CityStory;intro:string;exercise:string;deliverable:string;audience:string;sector:string};
const local:Record<string,[string,string,string,string,string]>={
 bordeaux:['À Bordeaux, formez votre équipe à utiliser l’IA sur ses vrais dossiers : préparer un échange commercial, structurer une synthèse et vérifier les réponses. Althoce accompagne les premiers essais jusqu’à leur application dans votre quotidien.','Préparer une réponse commerciale à partir d’une fiche produit et d’un échange client.','Un modèle de préparation réutilisable pour vos prochains échanges.','Négoce, services et équipes commerciales','commerce-distribution'],
 paris:['À Paris, vos équipes jonglent entre réunions, documents et décisions à préparer. Nos formations IA leur donnent une méthode commune pour synthétiser, rédiger et vérifier, avec leurs outils de travail.','Transformer des notes de réunion en une synthèse et un plan d’action sourcé.','Une trame de compte rendu et une checklist de relecture.','Conseil, fonctions support et directions','finance'],
 lyon:['À Lyon, apprenez à utiliser l’IA pour préparer les analyses et fluidifier le travail entre services. Les ateliers Althoce relient les exercices à vos documents, à votre niveau et aux responsabilités de chacun.','Comparer des propositions fournisseurs à partir de critères définis par l’équipe.','Une grille de comparaison à vérifier et à réutiliser.','Achats, industrie et services professionnels','industrie'],
 marseille:['À Marseille, nos formations IA aident vos collaborateurs à préparer les échanges et à organiser les dossiers. Chaque exercice relie un besoin concret, une consigne claire et une vérification humaine.','Regrouper les informations d’une demande et identifier les pièces manquantes.','Une fiche de préparation pour transmettre un dossier complet.','Commerce, logistique et administration','commerce-distribution'],
 toulouse:['À Toulouse, donnez à votre équipe des repères pour exploiter l’IA sans perdre la trace des sources. Nous travaillons sur la recherche documentaire, la préparation des réponses et la vérification.','Retrouver les passages utiles dans une documentation et préparer une réponse sourcée.','Une méthode pour relier chaque réponse à son document de référence.','Services techniques et équipes support','industrie'],
 nantes:['À Nantes, passez des essais individuels à une pratique partagée de l’IA. Les formations Althoce vous aident à préparer les contenus et les échanges en respectant votre manière de travailler.','Décliner un contenu de référence en plusieurs formats dans le ton de votre entreprise.','Un brief et une grille de validation éditoriale.','Communication, services et équipes projet','marketing-communication'],
 lille:['À Lille, apprenez à préparer plus facilement les demandes clients et les documents récurrents avec l’IA. Les exercices restent liés à votre activité et aux informations que votre équipe peut utiliser.','Préparer une réponse à une demande client à partir d’une base produit autorisée.','Une trame de réponse avec les points à confirmer avant envoi.','Distribution et relation client','commerce-distribution'],
 strasbourg:['À Strasbourg, formez vos équipes à structurer les informations et à préparer les échanges multilingues avec l’IA. Nous insistons sur le contexte, la qualité des sources et la relecture.','Préparer deux versions d’un message commercial et contrôler les informations clés.','Une checklist de vérification pour les communications multilingues.','Commerce et coordination de projets','commerce-distribution'],
 nice:['À Nice, nos formations IA partent des situations où vos équipes ont besoin de mieux préparer leurs réponses. L’objectif : une pratique utile, compréhensible et facile à reprendre après l’atelier.','Résumer l’historique d’une demande pour préparer sa transmission à un collègue.','Une fiche de passage de relais simple et sourcée.','Services et relation client','immobilier'],
 rennes:['À Rennes, accompagnez votre équipe vers des usages IA qui se partagent. Les ateliers donnent des repères pour rédiger, synthétiser et retrouver l’information sans dépendre d’un seul utilisateur.','Transformer une procédure interne en une fiche pratique pour un nouveau collègue.','Un support de transmission relu et validé par l’équipe.','Services et réseaux associatifs','associations'],
 montpellier:['À Montpellier, formez vos équipes à préparer leurs contenus et leurs analyses avec l’IA. Nous construisons les exercices à partir de votre public, de vos documents et de vos contraintes.','Construire un brief de contenu à partir d’un objectif et de messages validés.','Un modèle de brief pour guider les productions suivantes.','Communication et services','marketing-communication'],
 grenoble:['À Grenoble, apprenez à questionner des documents et à vérifier les réponses de l’IA. Nos ateliers privilégient la traçabilité des sources et la mise en pratique sur des dossiers représentatifs.','Préparer une synthèse de documents techniques avec références aux passages utiles.','Une grille de contrôle pour les synthèses documentaires.','Équipes techniques et achats','industrie'],
 dijon:['À Dijon, l’IA devient un outil de travail quand chacun sait quoi lui demander et quoi vérifier. Althoce forme vos collaborateurs à partir de tâches administratives et documentaires concrètes.','Extraire les éléments utiles d’un dossier pour préparer un tableau de suivi.','Une procédure de préparation et de contrôle des données.','Administration et équipes de gestion','finance'],
 reims:['À Reims, nos formations IA aident les équipes à préparer les échanges et à mieux structurer l’information. Les exercices s’adaptent à votre niveau et aux outils accessibles dans votre entreprise.','Préparer un argumentaire commercial à partir de données produit vérifiées.','Une trame de préparation qui conserve votre ton et vos points de contrôle.','Négoce et services commerciaux','commerce-distribution'],
 angers:['À Angers, donnez à vos équipes une méthode pour transformer les essais IA en usages réguliers. On pratique, on compare les réponses et on formalise les repères à garder.','Transformer des notes d’activité en un bilan structuré, sans inventer d’informations.','Un modèle de bilan et une liste des données à réunir.','Associations et fonctions support','associations'],
 'le-havre':['Au Havre, formez votre équipe à préparer les dossiers et les passages de relais avec l’IA. Les ateliers donnent une place claire aux données utilisées et à la personne qui valide.','Préparer une synthèse des échanges et des documents d’un dossier fournisseur.','Une fiche de suivi pour retrouver les pièces et les actions attendues.','Commerce et coordination opérationnelle','commerce-distribution'],
 'saint-etienne':['À Saint-Étienne, les formations IA Althoce relient les outils aux documents que vos équipes manipulent déjà. Nous travaillons la préparation, la comparaison et la vérification, étape par étape.','Comparer deux versions d’une procédure et préparer la liste des changements.','Une méthode de revue documentaire avec contrôle humain.','Industrie et qualité','industrie'],
 toulon:['À Toulon, apprenez à utiliser l’IA pour préparer les réponses et organiser les informations du quotidien. L’atelier met l’accent sur la qualité des consignes et la relecture avant partage.','Classer des demandes types et préparer leur orientation vers la bonne personne.','Une grille de qualification des demandes et de validation des réponses.','Services et administration','immobilier'],
 nimes:['À Nîmes, nos formations IA donnent à votre équipe des habitudes simples pour rédiger et synthétiser avec méthode. Les participants repartent avec des repères adaptés à leurs propres tâches.','Préparer un compte rendu d’activité et distinguer les faits des éléments à compléter.','Une trame de synthèse et une checklist de vérification.','Petites entreprises et réseaux associatifs','associations']
};
export const formationCities:LocalTraining[]=cityStories.map(city=>{const [intro,exercise,deliverable,audience,sector]=local[city.slug];return {city,intro,exercise,deliverable,audience,sector}});
export function trainingFaq(d:LocalTraining){const place=cityLocation(d.city);return [
 {q:`Comment organiser une formation IA ${place} ?`,a:`Nous échangeons d’abord sur les participants, leur niveau et leurs tâches. La formation ${place} peut être organisée sur site ou à distance selon les modalités convenues. Le lieu et le calendrier sont confirmés lors du cadrage.`},
 {q:'Quel programme choisir pour mon équipe ?',a:'IA Fondamentaux s’adresse aux débutants. IA Avancée approfondit une pratique déjà régulière. Le Coaching IA Dirigeant propose un accompagnement individuel. Les programmes détaillés précisent les prérequis et les objectifs.'},
 {q:`Quels exercices peut-on travailler ${place} ?`,a:`Un exemple : ${d.exercise} Les exercices sont adaptés à votre organisation et aux documents utilisables pendant l’atelier.`},
 {q:'Quelles sont les durées et la taille des groupes ?',a:'Les formations IA Fondamentaux et IA Avancée durent chacune 7 heures et accueillent jusqu’à 10 participants. Le coaching dirigeant comprend quatre séances individuelles de 1 h 30.'},
 {q:'Un financement OPCO est-il possible ?',a:'Une prise en charge peut être étudiée via notre organisme partenaire, selon votre situation et les conditions du financeur. Elle n’est pas automatique ; la demande se prépare avant la formation.'},
 {q:`Avez-vous un centre de formation permanent ${place} ?`,a:d.city.slug==='bordeaux'?'Althoce est ancré à Bordeaux. Le lieu et le format de la formation sont convenus ensemble, dans vos locaux ou à distance selon le besoin.':`Althoce est basé à Bordeaux et accompagne les équipes ${place}. Cette page présente une zone d’intervention, pas un centre local permanent. Le lieu et les modalités sont définis avec vous.`}
]}
