import type { Faq } from '@/components/brand/Sections';
export type ServiceStory = {
  slug: string; name: string; title: string; accent: string; description: string;
  image: string; alt: string; question: string; answer: string;
  exampleTitle: string; example: [string, string, string];
  uses: { title: string; text: string }[]; deliveryTitle: string; delivery: string[];
  next: string; faq: Faq[];
};
const cost = 'Le prix dépend du périmètre, des outils à connecter, des données et de l’accompagnement nécessaire. Le pré-audit offert de 30 minutes permet de faire connaissance ; le chiffrage intervient après un cadrage adapté.';
const timing = 'Le calendrier est défini au cadrage selon la complexité, les accès disponibles et le temps nécessaire aux essais avec vos équipes. Nous privilégions un premier périmètre utile, puis des améliorations progressives.';
const data = 'Nous choisissons avec vous les modèles, l’hébergement et les accès selon la sensibilité des données et vos exigences. Les flux et les prestataires sont identifiés au cadrage ; un hébergement en Europe est étudié lorsque votre contexte le demande.';
const transfer = 'La prise en main et une documentation accompagnent le déploiement. Les accès, les livrables transférés et les conditions de propriété sont précisés dans le périmètre contractuel, en tenant compte des licences tierces.';
export const serviceStories: ServiceStory[] = [
  {
    slug:'pilotage-ia', name:'Pilotage IA & maintenance', title:'Le pilotage IA.', accent:'Pour que l’utile le reste.',
    description:'Votre entreprise évolue. Vos agents IA et automatisations aussi. Althoce accompagne leur fiabilité, suit les usages et ajuste les solutions avec vos équipes, dans un cadre défini ensemble.',
    image:'pilotage', alt:'Trois collègues font le point sur un projet autour d’un ordinateur et de documents dans un bureau.',
    question:'Le projet est lancé. La relation continue.',
    answer:'Un outil déployé doit rester utile au quotidien. Nous écoutons les retours, observons ce qui fonctionne et choisissons avec vous les améliorations qui comptent vraiment.',
    exampleTitle:'Observer. Ajuster. Continuer à avancer.',
    example:['Faire le point sur les usages','Traiter les difficultés rencontrées','Prioriser la prochaine amélioration'],
    uses:[{title:'Suivre les usages.',text:'Comprendre ce qui est adopté, ce qui freine l’équipe et les tâches qui demandent encore trop d’effort.'},{title:'Entretenir les solutions.',text:'Examiner les erreurs et les connexions, puis apporter les corrections prévues dans le périmètre de maintenance.'},{title:'Faire évoluer ensemble.',text:'Adapter les règles et préparer de nouveaux usages lorsque vos outils ou votre organisation changent.'}],
    deliveryTitle:'Un suivi clair. Des équipes accompagnées.',
    delivery:['Un périmètre de suivi défini : solutions, interlocuteurs et modalités d’intervention.','Des points réguliers pour examiner les usages, les incidents et les priorités.','Un suivi des actions et des décisions, avec une documentation tenue à jour selon les évolutions.'],
    next:'Le pilotage s’inscrit dans un accompagnement annuel adapté à votre contexte. Les évolutions importantes et les formations complémentaires sont cadrées avec vous avant d’être engagées.',
    faq:[
      {q:'Quelle différence entre pilotage IA et maintenance ?',a:'La maintenance vise le bon fonctionnement des solutions dans le périmètre convenu. Le pilotage regarde aussi les usages, les difficultés des équipes et les priorités d’évolution. Les deux se complètent pour faire durer la valeur du projet.'},
      {q:'Qu’est-ce qui est inclus après un déploiement Althoce ?',a:'Le déploiement comprend la prise en main, la documentation et un mois de maintenance. Les points à 30 et 90 jours servent à suivre les usages. Le pilotage dans la durée fait l’objet d’un accompagnement distinct, dont le périmètre est précisé ensemble.'},
      {q:'Comment se déroule l’accompagnement annuel ?',a:'Nous définissons les solutions suivies, les interlocuteurs, le rythme des points et les modalités d’intervention. Les observations et les actions sont partagées pour décider ensemble de la suite.'},
      {q:'Les nouvelles fonctionnalités sont-elles toutes incluses ?',a:'Les corrections, ajustements et évolutions couverts sont précisés dans le périmètre. Une nouvelle fonctionnalité ou un changement important peut nécessiter un cadrage et un chiffrage complémentaires, validés avant intervention.'},
      {q:'Comment sont traités les incidents ?',a:'Les canaux de signalement, les priorités et les modalités de réponse sont convenus selon la criticité des solutions. Les horaires et délais éventuels sont précisés dans le contrat, sans promesse universelle de disponibilité permanente.'},
      {q:'Peut-on faire évoluer les compétences des équipes ?',a:'Oui. Le suivi permet de repérer les besoins de prise en main et de formation IA. Des sessions adaptées peuvent être proposées et cadrées en complément pour renforcer l’autonomie des utilisateurs.'},
      {q:'Combien coûte le pilotage IA ?',a:'Le coût dépend du nombre de solutions, de leur complexité, de leur criticité et du niveau d’accompagnement. Le pré-audit offert de 30 minutes permet de faire le point avant de définir un périmètre et un chiffrage.'}
    ]
  },

  {
    slug:'audit-ia', name:'Audit IA', title:'Audit IA : choisissez', accent:'ce qui mérite votre énergie.',
    description:'Notre diagnostic IA part du travail réel de votre PME. Nous repérons les usages utiles, estimons leur impact et construisons une feuille de route pour avancer dans le bon ordre.',
    image:'diagnostic', alt:'Une consultante et un dirigeant examinent des documents autour d’une table de bureau.',
    question:'Par où commencer avec l’IA ?', answer:'Par ce qui pèse déjà sur vos équipes. Nous observons avant de recommander : mieux utiliser un logiciel, former, automatiser ou développer.',
    exampleTitle:'D’une tâche qui revient à une priorité claire.', example:['Observer le travail réel','Mesurer l’effort et les contraintes','Choisir les usages à lancer'],
    uses:[{title:'Voir ce qui prend du temps.',text:'Entretiens, observation des tâches, ressaisies et détours entre vos outils.'},{title:'Distinguer l’utile du possible.',text:'Impact estimé, faisabilité et risques confrontés à vos dossiers et à votre organisation.'},{title:'Décider avec des repères.',text:'Des priorités lisibles pour investir dans les bons usages et préparer les équipes.'}],
    deliveryTitle:'Vous repartez avec un cap.', delivery:['Une feuille de route sur six mois et des priorités chiffrées.','Une bibliothèque de prompts adaptée aux usages retenus.','Une note de conformité RGPD et AI Act, selon votre contexte.'],
    next:'Le diagnostic recommande et chiffre. Les déploiements et les formations sont ensuite cadrés séparément, selon vos priorités.',
    faq:[{q:'Quelle est la différence entre les 30 minutes offertes et l’audit IA Althoce ?',a:'Le pré-audit offert est un premier échange pour comprendre votre situation. Le diagnostic complet est une mission distincte : immersion, mesure, qualification des usages, priorisation et restitution d’une feuille de route.'},{q:'Combien coûte un audit IA chez Althoce ?',a:cost},{q:'Combien de temps prend un audit IA ?',a:'La durée dépend du nombre de métiers, des processus étudiés et de la disponibilité des équipes. Le périmètre et le calendrier sont définis par écrit avant la mission.'},{q:'Faut-il déjà utiliser des outils IA ?',a:'Non. Le diagnostic peut partir de vos logiciels et de votre façon de travailler actuelle. Il peut aussi recommander une formation ou une meilleure configuration plutôt qu’un développement.'},{q:'Comment estimez-vous le retour sur investissement ?',a:'Nous partons des tâches observées, de leur fréquence et du temps consacré. Les hypothèses, les coûts et les limites de l’estimation sont explicités : un gain estimé reste à confirmer dans les usages.'},{q:'Pouvez-vous étudier une solution IA déjà en place ?',a:'Oui, le cadrage peut inclure les outils existants, les difficultés rencontrées et les usages réels. Nous définissons ensemble ce qui doit être examiné et les accès nécessaires.'}]
  },
  {
    slug:'agents-ia',name:'Agents IA',title:'Des agents IA sur mesure.',accent:'Du temps pour votre métier.',
    description:'Nous créons des agents IA sur mesure, adaptés à vos processus, vos outils et vos équipes. Chaque projet part du contexte de votre entreprise, avec des règles et une prise en main définies ensemble.',
    image:'construction',alt:'Deux spécialistes travaillent ensemble à la conception d’une solution dans un bureau.',
    question:'Votre entreprise a sa façon de travailler.',answer:'Votre agent IA doit la comprendre. Nous concevons ses tâches, ses connexions et ses validations à partir de vos situations réelles. Les agents présentés sur le site sont des exemples d’usages, à personnaliser avec vous.',
    exampleTitle:'Une demande reçue. Une suite déjà préparée.',example:['Lire et qualifier la demande','Préparer l’action dans vos outils','Vous laisser valider si nécessaire'],
    uses:[{title:'Commercial.',text:'Préparer une fiche prospect, synthétiser un échange et proposer une relance.'},{title:'Opérations.',text:'Extraire les informations d’un document et préparer la mise à jour d’un dossier.'},{title:'Service client.',text:'Retrouver une réponse dans vos ressources et préparer le traitement d’une demande.'}],
    deliveryTitle:'Un agent utile. Une équipe qui sait s’en servir.',delivery:['Un périmètre, des accès et des règles de validation définis.','Des essais sur vos cas réels et une intégration à vos outils.','Une prise en main, une documentation et un mois de maintenance au déploiement.'],next:'Nous suivons les usages à 30 et 90 jours. Des formations IA peuvent compléter le transfert pour aider l’équipe à aller plus loin.',
    faq:[{q:'Les agents présentés sont-ils des solutions prêtes à acheter ?',a:'Ce sont des exemples pour vous aider à vous projeter. Nous créons votre agent IA sur mesure après avoir compris vos processus, vos données, vos outils et les validations nécessaires.'},{q:'Quelle est la différence entre un agent IA et un chatbot ?',a:'Le chatbot est une interface de conversation. Un agent IA peut aussi utiliser des outils pour exécuter des actions autorisées. Un chatbot connecté à des outils peut donc intégrer des capacités d’agent.'},{q:'Quelle est la différence avec une automatisation classique ?',a:'Une automatisation suit des règles définies. Un agent peut utiliser un modèle IA pour interpréter une information ou choisir une action dans un cadre donné. Les deux approches peuvent être combinées.'},{q:'Combien coûte la création d’un agent IA ?',a:cost},{q:'En combien de temps est-il opérationnel ?',a:timing},{q:'Que récupérons-nous à la fin de la mission ?',a:transfer},{q:'Où passent les données de l’entreprise ?',a:data},{q:'L’agent remplace-t-il les salariés ?',a:'Notre accompagnement vise à alléger les tâches répétitives et à renforcer les compétences des équipes. Les responsabilités et les décisions sensibles restent définies avec vous ; nous ne promettons pas l’automatisation complète d’un poste.'},{q:'Quelle différence avec un employé IA ?',a:'Le terme employé IA désigne ici un assistant dédié à plusieurs tâches liées à un rôle. Il reste un système logiciel avec un périmètre et une supervision, et non un salarié autonome.'}]
  },
  {
    slug:'automatisation-ia',name:'Automatisation IA',title:'L’automatisation IA sur mesure.',accent:'À votre façon de travailler.',
    description:'Nous créons des automatisations IA personnalisées pour votre entreprise : vos processus, vos logiciels, vos règles et vos exceptions. Chaque parcours est construit avec les équipes qui l’utilisent.',
    image:'construction',alt:'Deux collègues ajustent une solution de travail sur leurs ordinateurs.',
    question:'Encore la même information à recopier ?',answer:'Nous observons comment le travail circule chez vous, puis concevons les connexions et les règles adaptées. Les parcours présentés ici illustrent ce que nous pouvons construire : votre automatisation se définit à partir de votre contexte.',
    exampleTitle:'Du document reçu au dossier prêt à vérifier.',example:['Recevoir un document','Extraire et organiser les données','Préparer la mise à jour du dossier'],
    uses:[{title:'Mails et documents.',text:'Trier les demandes et extraire les informations utiles, avec contrôle des cas ambigus.'},{title:'CRM et suivi commercial.',text:'Synchroniser les informations et préparer les relances selon vos règles.'},{title:'Reporting et opérations.',text:'Rassembler les données et préparer les synthèses sans multiplier les ressaisies.'}],
    deliveryTitle:'Un processus plus fluide, dans vos outils.',delivery:['Un parcours métier défini, avec les exceptions et les validations.','Des automatisations testées sur des cas représentatifs.','Documentation, prise en main et un mois de maintenance inclus au déploiement.'],next:'Nous observons ensuite ce qui est réellement utilisé et ajustons avec vous. La formation aide vos équipes à comprendre et à piloter le nouveau fonctionnement.',
    faq:[{q:'Vos automatisations sont-elles personnalisées ?',a:'Oui. Les exemples du site illustrent des possibilités. Nous construisons chaque automatisation selon vos processus, les logiciels disponibles, vos données, vos exceptions et les responsabilités de vos équipes.'},{q:'Qu’est-ce que l’automatisation IA ?',a:'Elle combine des règles de workflow et des capacités IA pour traiter des informations comme des mails ou des documents. Les étapes fiables sont automatisées, les cas à vérifier sont orientés vers une personne.'},{q:'Quels processus peut-on automatiser ?',a:'Les tâches fréquentes, suffisamment définies et alimentées par des données accessibles sont de bons candidats. Nous évaluons les exceptions, le coût et les contraintes avant de recommander un projet.'},{q:'Faut-il changer nos logiciels ?',a:'Nous privilégions les outils existants lorsque leurs connecteurs, API et droits d’accès le permettent. Une limite technique est identifiée avant d’engager le déploiement.'},{q:'Combien coûte une automatisation IA ?',a:cost},{q:'Quel délai prévoir ?',a:timing},{q:'Comment gardons-nous le contrôle ?',a:'Les autorisations, les validations humaines, les alertes et les modalités d’arrêt sont définies selon les actions confiées au système.'},{q:'Comment mesurez-vous les résultats ?',a:'Nous comparons les usages et les tâches concernées avec la situation de départ : temps consacré, erreurs, exceptions et adoption. Les gains estimés au cadrage sont confrontés au travail réel.'}]
  },
  {
    slug:'integration-ia',name:'Intégration IA',title:'L’intégration IA.',accent:'Dans les outils de votre quotidien.',
    description:'Votre CRM, vos documents, votre messagerie : nous connectons l’IA à votre système d’information, avec les accès et les règles adaptés à votre entreprise.',
    image:'construction',alt:'Deux spécialistes examinent ensemble une intégration sur leurs postes de travail.',
    question:'Une solution utile doit trouver sa place.',answer:'Nous partons de votre environnement et échangeons avec les métiers et les responsables techniques. L’objectif : faire circuler l’information sans ajouter un outil isolé.',
    exampleTitle:'La bonne information. Au bon endroit.',example:['Accéder aux sources autorisées','Relier vos applications','Suivre et contrôler les échanges'],
    uses:[{title:'CRM et ERP.',text:'Relier les dossiers et les actions aux applications déjà utilisées.'},{title:'Documents et connaissances.',text:'Rendre les ressources utiles accessibles selon les droits de chaque personne.'},{title:'Messagerie et collaboration.',text:'Intégrer les demandes et notifications à vos habitudes de travail.'}],
    deliveryTitle:'Des connexions comprises et maîtrisées.',delivery:['Les flux de données, accès et contraintes identifiés avec vous.','Des connexions testées, avec gestion des erreurs et reprise adaptée.','Une documentation pour l’exploitation et une prise en main accompagnée.'],next:'Les choix d’hébergement et de modèles dépendent de vos exigences. Les points de contrôle sont convenus avec vos interlocuteurs métiers et techniques.',
    faq:[{q:'Comment l’IA accède-t-elle à nos logiciels ?',a:'Nous étudions les connecteurs, API et mécanismes d’authentification disponibles. Les droits sont limités au périmètre nécessaire et les secrets doivent être gérés dans un environnement adapté.'},{q:'Mes données transitent-elles par un fournisseur de modèle ?',a:data},{q:'Comment gérez-vous les permissions ?',a:'Les accès sont définis à partir des rôles, des sources et des actions autorisées. Nous vérifions avec vous comment les droits de vos outils se répercutent dans l’intégration.'},{q:'Combien coûte une intégration IA ?',a:cost},{q:'Comment abordez-vous le RGPD ?',a:'Le cadrage identifie les données traitées, les finalités, les prestataires, la conservation et les droits d’accès. Les mesures nécessaires sont déterminées avec vos responsables, selon les usages retenus.'},{q:'Peut-on interrompre une automatisation ?',a:'Les modalités d’arrêt, d’alerte et de reprise sont définies et testées selon les risques du processus. Vos équipes disposent des consignes nécessaires pour intervenir.'}]
  },
  {
    slug:'developpement-ia',name:'Développement IA',title:'Du développement IA sur mesure.',accent:'Pour un besoin qui vous ressemble.',
    description:'Quand les outils existants ne suffisent pas, Althoce conçoit la solution adaptée : agents IA, applications métier et intégrations. Construite avec vos équipes, pensée pour être utilisée.',
    image:'construction',alt:'Deux développeurs confrontent leurs idées devant leurs écrans dans un bureau lumineux.',
    question:'Votre façon de travailler a ses particularités.',answer:'Nous développons ce qui manque réellement. Le choix entre configuration, automatisation et code sur mesure dépend de votre besoin et de la vie future de la solution.',
    exampleTitle:'D’une idée métier à un outil que l’on adopte.',example:['Définir le besoin ensemble','Tester une première version','Déployer et transmettre'],
    uses:[{title:'Applications métier.',text:'Une interface adaptée à vos tâches, à vos règles et aux personnes qui l’utilisent.'},{title:'Agents et assistants.',text:'Des fonctionnalités IA reliées à vos sources et aux actions autorisées.'},{title:'Intégrations spécifiques.',text:'Du code sur mesure pour relier ou compléter les outils de votre organisation.'}],
    deliveryTitle:'Vous comprenez ce qui est construit.',delivery:['Un périmètre et des critères de validation partagés.','Des versions testées avec vos équipes sur vos cas d’usage.','Les livrables convenus, la documentation et le transfert de prise en main.'],next:'Nous préparons aussi l’après : suivi des erreurs, maintenance et évolution. Vos interlocuteurs techniques participent aux décisions qui les concernent.',
    faq:[{q:'Faut-il forcément développer une solution sur mesure ?',a:'Non. Nous étudions d’abord les outils existants et leur configuration. Le développement sur mesure est retenu lorsqu’il répond à un besoin que ces options ne couvrent pas correctement.'},{q:'Le code livré nous appartient-il ?',a:transfer},{q:'Quelles technologies utilisez-vous ?',a:'Les technologies sont choisies selon le besoin et votre environnement. Elles peuvent inclure Python, TypeScript, des API de modèles IA et des outils d’orchestration comme n8n ; la maintenabilité compte autant que le choix initial.'},{q:'Combien coûte un développement IA ?',a:cost},{q:'Travaillez-vous avec les DSI ou les métiers ?',a:'Nous associons les personnes qui utilisent la solution et celles qui en assurent le fonctionnement. Les interlocuteurs et les validations sont définis au cadrage.'},{q:'Comment vérifiez-vous la qualité de la solution ?',a:'Nous définissons des cas de test représentatifs, des critères d’acceptation et un suivi adapté aux usages. Les résultats des modèles, les erreurs et les coûts sont examinés selon le périmètre du projet.'}]
  },
  {
    slug:'chatbot-ia',name:'Chatbot IA',title:'Un chatbot IA.',accent:'Vos connaissances à portée de réponse.',
    description:'Un assistant conversationnel connecté à vos ressources pour aider vos clients ou vos équipes à trouver l’information. Des réponses contextualisées, avec un relais humain prévu.',
    image:'support',alt:'Une professionnelle du support et un collègue examinent une demande dans un bureau.',
    question:'La réponse existe. Encore faut-il la retrouver.',answer:'Un chatbot RAG recherche des passages dans vos documents avant de formuler une réponse. Nous préparons les sources, les droits et les limites avec vos équipes.',
    exampleTitle:'Une question. Vos sources. Une réponse à vérifier.',example:['Comprendre la question','Retrouver les passages utiles','Répondre ou passer le relais'],
    uses:[{title:'Accompagner vos visiteurs.',text:'Répondre aux questions courantes sur vos offres à partir de contenus validés.'},{title:'Aider le support.',text:'Retrouver une procédure et préparer une réponse sans fouiller plusieurs dossiers.'},{title:'Partager les connaissances.',text:'Faciliter l’accès aux ressources internes, selon les droits de l’utilisateur.'}],
    deliveryTitle:'Un assistant qui connaît son périmètre.',delivery:['Des sources sélectionnées et un mode de mise à jour défini.','Des réponses testées, des limites explicites et un relais vers une personne.','Une intégration adaptée au site ou à l’espace interne, avec prise en main.'],next:'La qualité des réponses dépend aussi de vos contenus. Nous aidons vos équipes à organiser et à maintenir cette connaissance dans la durée.',
    faq:[{q:'Quelle différence entre un chatbot et un agent IA ?',a:'Un chatbot désigne une interface de conversation. Il peut répondre à partir de documents et, s’il est connecté à des outils, déclencher des actions comme un agent. Le périmètre est défini selon vos besoins.'},{q:'Comment limitez-vous les réponses inventées ?',a:'Nous sélectionnons les sources, testons les réponses et prévoyons le recours à une personne lorsque l’information manque. Le RAG réduit certains risques, mais ne garantit pas l’absence d’erreurs.'},{q:'Combien coûte un chatbot IA ?',a:cost},{q:'En combien de temps est-il opérationnel ?',a:timing},{q:'Est-il intégrable à notre site existant ?',a:'L’intégration dépend de votre site et de ses possibilités techniques : module embarqué, API ou interface dédiée. La compatibilité et les accès sont vérifiés au cadrage.'},{q:'Le chatbot apprend-il tout seul ?',a:'Sa base de connaissances doit être entretenue. Nous définissons comment ajouter, corriger et retirer des contenus ; les échanges ne deviennent pas automatiquement des informations de référence.'}]
  },
  {
    slug:'employe-ia',name:'Employé IA',title:'Un employé IA dédié.',accent:'Un appui pour votre équipe.',
    description:'Un assistant IA qui prend en charge un ensemble de tâches liées à un rôle : préparation commerciale, support ou opérations. Un périmètre progressif et une supervision humaine définie.',
    image:'support',alt:'Deux collègues du service client préparent ensemble le traitement d’une demande.',
    question:'Plusieurs tâches liées. Un même appui au quotidien.',answer:'L’expression « employé IA » décrit ici un système logiciel dédié. Nous organisons les tâches, les accès et les passages de relais pour aider votre équipe à avancer.',
    exampleTitle:'Préparer la journée, sans décider à votre place.',example:['Rassembler les informations','Préparer les actions courantes','Soumettre les décisions à l’équipe'],
    uses:[{title:'Appui commercial.',text:'Préparer les dossiers, résumer les échanges et proposer les prochaines actions.'},{title:'Appui au support.',text:'Qualifier une demande, rechercher une réponse et préparer le relais adapté.'},{title:'Appui aux opérations.',text:'Organiser les pièces d’un dossier et suivre les étapes répétitives.'}],
    deliveryTitle:'Un rôle précis, des responsabilités claires.',delivery:['Les tâches confiées au système et celles qui restent humaines.','Des essais progressifs avant d’élargir les actions autorisées.','Une formation à la supervision, une documentation et un suivi après déploiement.'],next:'L’objectif est d’alléger la charge répétitive. Les arbitrages sensibles, la relation et la responsabilité restent entre les mains des personnes désignées.',
    faq:[{q:'Quelle différence entre un agent IA et un employé IA ?',a:'Un agent couvre un objectif précis. Un employé IA regroupe plusieurs tâches liées à un rôle, avec des outils et des règles de supervision. Il s’agit d’un assistant logiciel, pas d’un salarié autonome.'},{q:'Va-t-il remplacer mes salariés ?',a:'Notre démarche vise à soutenir les équipes sur les tâches répétitives et à développer leurs compétences. Nous cadrons les responsabilités humaines et ne promettons pas de remplacer un poste entier.'},{q:'Combien coûte un employé IA ?',a:cost},{q:'Quel délai prévoir avant le déploiement ?',a:timing},{q:'Mes données restent-elles en France ?',a:data},{q:'Peut-on le relier à nos outils existants ?',a:'Les connexions sont étudiées selon vos logiciels, leurs API et les droits disponibles. Nous privilégions les outils déjà utilisés lorsque leur intégration est possible.'},{q:'Que se passe-t-il face à un cas qu’il ne sait pas traiter ?',a:'Les cas incertains et les limites du périmètre doivent déclencher un passage de relais. Ces situations sont testées avec votre équipe ; le système ne doit pas être considéré comme infaillible.'},{q:'Comment l’équipe apprend-elle à travailler avec lui ?',a:'Le déploiement comprend la prise en main et la documentation. Des formations et des points de suivi permettent de comprendre les limites, de vérifier les résultats et d’ajuster les usages.'}]
  }
];
export const hubFaq: Faq[] = [
 {q:'Par quel service commencer ?',a:'Le pré-audit offert permet d’échanger sur votre situation. Si les priorités restent à clarifier, un diagnostic est pertinent. Si le besoin est déjà défini, nous pouvons cadrer directement une formation ou un déploiement.'},
 {q:'Quelle différence entre agent IA, automatisation et employé IA ?',a:'Un agent poursuit un objectif précis, une automatisation relie les étapes d’un processus et un employé IA regroupe plusieurs tâches liées à un rôle. Ces solutions peuvent se combiner et restent encadrées par des règles et des responsabilités humaines.'},
 {q:'Comment se passe le premier échange ?',a:'Le pré-audit offert dure 30 minutes, sans engagement. Nous parlons de vos besoins, de vos outils et des pistes à explorer. Le diagnostic complet et le chiffrage d’un projet sont des étapes distinctes.'},
 {q:'Proposez-vous aussi des formations IA ?',a:'Oui. Les formations et le coaching partent des usages de vos équipes. Ils peuvent constituer un accompagnement à part entière ou compléter un déploiement.'},
 {q:'Faut-il combiner plusieurs services ?',a:'Cela dépend de votre besoin. Nous construisons un périmètre utile : formation, configuration, automatisation ou développement. Le pilotage peut ensuite accompagner les usages dans la durée.'}
];
