import Image from 'next/image';
import AgentMarquee from '../AgentMarquee';
import { ArrowUpRight, ArrowRight, Layers3, ShieldCheck, ChartNoAxesCombined, Megaphone, Handshake, Headphones, Phone, Users, ReceiptText, Settings2, Scale, ShoppingBag } from 'lucide-react';
import { FaqSection, PreAuditCTA, TextLink } from '../brand/Sections';
import TrustStrip from '../brand/TrustStrip';
import { MissionPath, ServiceLinks } from '../services/ServicePage';
import { metierStories, type MetierStory } from '@/lib/metiers-content';
import b from '../brand/Brand.module.css';
import s from './Metiers.module.css';
const cases:Record<string,string>={marketing:'saas-b2b-agent-ia-marketing',commercial:'negoce-vins-bordelais-agent-ia-sdr',finance:'cabinet-comptable-lyon',operations:'distributeur-b2b-agent-ia-ops',rh:'cabinet-recrutement-paris-agent-ia-tri-cv',juridique:'eti-agroalimentaire-agent-ia-juridique',achats:'eti-industrielle-agent-ia-achats','service-client':'saas-b2b-agent-ia-service-client',telephonique:'cabinet-avocats-agent-ia-telephonique'};
const icons:Record<string,typeof Megaphone>={marketing:Megaphone,commercial:Handshake,'service-client':Headphones,telephonique:Phone,rh:Users,finance:ReceiptText,operations:Settings2,juridique:Scale,achats:ShoppingBag};
export function MetierDirectory({current}:{current?:string}){return <nav className={s.directory} aria-label="Agents IA par métier">{metierStories.filter(x=>x.slug!==current).map(x=>{const Icon=icons[x.slug];return <a key={x.slug} href={`/agent-ia/${x.slug}/`}><span className={s.directoryIcon}><Icon size={21} strokeWidth={1.5} aria-hidden="true"/></span><span>{x.name}<small>{x.promise}</small></span><ArrowUpRight size={20} aria-hidden="true"/></a>})}</nav>}
export default function MetierPage({story:d}:{story:MetierStory}){return <main className={b.page}>
 <section className={s.hero}><div className={`${b.container} ${s.grid}`}><div><nav className={b.breadcrumb} aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span><a href="/agent-ia/">Agents IA par métier</a><span>/</span><span aria-current="page">{d.name}</span></nav><h1>{d.name}.<br/><span>{d.promise}</span></h1><p className={b.lead}>{d.intro}</p><a href="/contact/" className={b.primary}>Parlons de votre quotidien<ArrowUpRight size={18} aria-hidden="true"/></a><p className={s.note}>Un usage à imaginer ensemble. Une solution conçue pour vous.</p></div><div className={s.photo}><Image src={`/images/services/${d.image}.webp`} alt={`Des collègues travaillent ensemble sur des dossiers dans un bureau, pour illustrer les usages de l’${d.name.toLowerCase()}.`} fill priority sizes="(max-width:900px) 90vw, 50vw"/></div></div></section>
 <TrustStrip className={b.container}/>
 <section className={b.section} id="agents"><div className={b.container}><div className={s.heading}><h2>Ça commence<br/><span>dans votre quotidien.</span></h2><p>{d.situation}</p></div><div className={s.scenario}>{d.example.map((x,i)=><div key={x}><span className={s.number}>0{i+1}</span><p>{x}</p>{i<2&&<ArrowRight className={s.connector} size={22} aria-hidden="true"/>}</div>)}</div><p className={s.note}>Un scénario illustratif, à adapter à vos outils, vos données et vos règles.</p><div className={s.uses}>{d.uses.map((x,i)=><article key={x.title}><span aria-hidden="true">0{i+1}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></div></section>
 <section className={`${b.section} ${s.soft}`}><div className={`${b.container} ${s.grid}`}><div><h2>Le sur-mesure,<br/><span>c’est ce qui fait la différence.</span></h2><p className={b.lead}>Nous observons le travail réel avant de choisir les outils. Puis nous testons un premier périmètre avec les personnes qui l’utiliseront.</p><TextLink href="/services/audit-ia/">Partir du terrain avec un diagnostic IA</TextLink></div><div className={s.context}><article><Layers3 size={22} strokeWidth={1.5} aria-hidden="true"/><div><strong>Vos outils</strong><p>{d.tools}</p></div></article><article><ShieldCheck size={22} strokeWidth={1.5} aria-hidden="true"/><div><strong>Vos règles</strong><p>{d.guard}</p></div></article><article><ChartNoAxesCombined size={22} strokeWidth={1.5} aria-hidden="true"/><div><strong>Vos repères de progrès</strong><p>{d.measure} Les objectifs se fixent après observation du point de départ.</p></div></article></div></div></section>
 <section className={b.section}><div className={`${b.container} ${s.grid}`}><div className={s.photo}><Image src="/images/home/atelier-equipes.webp" alt="Une équipe pratique ensemble pendant un atelier de prise en main." fill sizes="(max-width:900px) 90vw, 50vw"/></div><div><h2>L’outil compte.<br/><span>L’équipe fait la suite.</span></h2><p className={b.lead}>Essais sur vos cas réels, documentation, formation à l’usage et suivi après le lancement : nous préparons l’adoption avec vous.</p><div className={s.followup}><div><strong>Prendre en main</strong><p>Des consignes claires pour utiliser, vérifier et reprendre la main.</p></div><div><strong>Faire durer</strong><p>Un mois de maintenance au déploiement, puis un pilotage continu à définir selon vos besoins.</p></div></div><TextLink href="/services/formation-ia/">Former vos équipes à l’IA</TextLink><br/><TextLink href="/services/pilotage-ia/">Prévoir le suivi dans la durée</TextLink></div></div></section>
 <section className={`${b.section} ${s.soft}`}><div className={b.container}><div className={s.heading}><h2>De votre besoin<br/><span>à un usage qui tient.</span></h2><p>Un accompagnement de A à Z, avec des points de validation tout au long de la mission.</p></div><MissionPath/><div className={s.links}><TextLink href="/a-propos/">Rencontrer le cabinet</TextLink><TextLink href={`/cas-clients/${cases[d.slug]}/`}>Explorer un cas dans ce métier</TextLink></div><ServiceLinks/></div></section>
 <FaqSection id="faq" title={`Vos questions sur l’${d.name.toLowerCase()}.`} description="Le périmètre, les outils et la place de votre équipe." items={d.faq}/>
 <PreAuditCTA id="footer-pre-audit"/>
 <section className={s.marqueeSection}><div className={b.container}><AgentMarquee/></div></section>
 </main>}
