import Image from 'next/image';
import { ArrowUpRight, MapPin, Monitor, Users, Compass } from 'lucide-react';
import { cityStories, cityFaq, cityLocation, type CityStory } from '@/lib/cities-content';
import { FaqSection, PreAuditCTA, TextLink } from '../brand/Sections';
import TrustStrip from '../brand/TrustStrip';
import CityMarquee from './CityMarquee';
import b from '../brand/Brand.module.css';
import s from './Cities.module.css';
export function CityLinks({slugs}:{slugs?:string[]}){return <nav className={s.cityLinks} aria-label="Accompagnement IA par ville">{(slugs?slugs.map(x=>cityStories.find(d=>d.slug===x)!):cityStories).map(d=><a key={d.slug} href={`/agence-ia-${d.slug}/`}><span>{d.name}<small>{d.region}</small></span><ArrowUpRight size={18} aria-hidden="true"/></a>)}</nav>}
function Offers(){return <div className={s.offers}>{[{title:'Comprendre',text:'Identifier les usages qui valent la peine d’être testés.',href:'/services/audit-ia/',link:'Diagnostic IA'},{title:'Équiper',text:'Former vos collaborateurs et accompagner les dirigeants.',href:'/services/formation-ia/',link:'Formations IA'},{title:'Automatiser',text:'Concevoir vos agents et vos automatisations sur mesure.',href:'/services/agents-ia/',link:'Agents IA sur mesure'},{title:'Faire durer',text:'Prévoir le pilotage, la maintenance et les évolutions.',href:'/services/pilotage-ia/',link:'Pilotage IA'}].map((x,i)=><article key={x.title}><span>0{i+1}</span><h3>{x.title}</h3><p>{x.text}</p><TextLink href={x.href}>{x.link}</TextLink></article>)}</div>}
export function CitySchema({story:d}:{story?:CityStory}){const url=d?`https://althoce.com/agence-ia-${d.slug}/`:'https://althoce.com/agences/';return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'Service','@id':`${url}#service`,name:d?`Conseil, formation et agents IA ${cityLocation(d)}`:'Accompagnement IA des PME en France',url,provider:{'@type':'Organization','@id':'https://althoce.com/#organization',name:'Althoce'},areaServed:d?{'@type':'City',name:d.name}:{'@type':'Country',name:'France'}},...(d?[{'@type':'FAQPage',mainEntity:cityFaq(d).map(x=>({'@type':'Question',name:x.q,acceptedAnswer:{'@type':'Answer',text:x.a}}))}]:[{'@type':'ItemList',itemListElement:cityStories.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,url:`https://althoce.com/agence-ia-${x.slug}/`}))}]),{'@type':'BreadcrumbList',itemListElement:[{name:'Accueil',url:'https://althoce.com/'},{name:'Althoce en France',url:'https://althoce.com/agences/'},...(d?[{name:d.name,url}]:[])].map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:x.url}))}]})}}/>}
export default function CityPage({story:d}:{story:CityStory}){return <main className={b.page}>
<section className={s.hero}><div className={b.container}><nav className={b.breadcrumb} aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span><a href="/agences/">Althoce en France</a><span>/</span><span aria-current="page">{d.name}</span></nav><div className={s.heroGrid}><div><h1>Agence IA {cityLocation(d)}.<br/><span>Votre contexte.<br/>Votre solution.</span></h1><p className={b.lead}>{d.intro}</p><TextLink href="/contact/">Parlons de votre entreprise</TextLink><p className={s.territory}><MapPin size={15} aria-hidden="true"/>{d.region}</p></div><div className={s.landmark}><Image src={`/images/cities/${d.slug}.webp`} alt={d.landmark+' à '+d.name} fill priority sizes="(max-width:900px) 90vw, 50vw"/><span>{d.name}<small>{d.landmark}</small></span></div></div></div></section>
<TrustStrip className={b.container}/>
<section className={b.section}><div className={b.container}><div className={s.heading}><h2>Partir de votre terrain.<br/><span>Choisir où agir.</span></h2><p>{d.focus}</p></div><div className={s.uses}>{d.uses.map((x,i)=><article key={x.title}><span className={s.number}>0{i+1}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div><p className={s.note}>Des exemples d’usages à adapter à votre entreprise, ses outils et ses règles.</p><TextLink href={`/agent-ia/${d.metier}/`}>Explorer un métier plus en détail</TextLink></div></section>
<section className={`${b.section} ${s.soft}`}><div className={b.container}><div className={s.heading}><h2>Un accompagnement.<br/><span>De l’idée à l’usage.</span></h2><p>Cabinet IA ancré à Bordeaux, Althoce relie conseil, formation et réalisation. Les agents IA ne sont pas des produits à choisir dans un catalogue : nous les construisons avec vous.</p></div><Offers/></div></section>
<section id="formations" aria-labelledby="formations-title" className={`${b.section} ${s.formations}`}>
  <div className={b.container}>
    <div className={s.formationIntro}>
      <div>
        <h2 id="formations-title">Formations IA {cityLocation(d)}.<br/><span>Faites grandir les compétences.</span></h2>
        <p className={b.lead}>Pour vos équipes comme pour les dirigeants, nos formations IA partent de vos vrais dossiers. Apprenez à utiliser les outils avec recul et à transformer les premiers essais en habitudes utiles.</p>
        <TextLink href="/services/formation-ia/">Découvrir les programmes de formation</TextLink>
      </div>
      <div className={s.formationPhoto}>
        <Image src="/images/services/formation.webp" alt="Des collaborateurs expérimentent l’IA ensemble pendant un atelier de formation" fill sizes="(max-width:900px) 90vw, 40vw"/>
        <span><Users size={18} aria-hidden="true"/>Apprendre ensemble. Pratiquer vraiment.</span>
      </div>
    </div>

  </div>
</section>
<section className={`${b.section} ${s.soft}`}><div className={b.container}><div className={s.heading}><h2>Proches du travail.<br/><span>Où que vous soyez.</span></h2><p>Nous accompagnons les entreprises {cityLocation(d)} et sur l’ensemble du territoire. Les échanges à distance et les ateliers sur site sont organisés selon le périmètre convenu.</p></div><div className={s.presence}><article><Monitor size={25} aria-hidden="true"/><h3>Des échanges réguliers</h3><p>Des points de travail avec les personnes concernées pour avancer et valider les étapes.</p></article><article><Compass size={25} aria-hidden="true"/><h3>Un cadre partagé</h3><p>Les accès, les données, les validations et les modalités de suivi sont définis avec votre équipe.</p></article></div><TextLink href="/a-propos/">Découvrir le cabinet Althoce</TextLink></div></section>
<FaqSection id="faq" title={`Votre projet IA ${cityLocation(d)}.`} description="Les réponses pour préparer un premier échange." items={cityFaq(d)}/><PreAuditCTA/><section className={s.near}><div className={b.container}><h2>Nous accompagnons aussi<br/><span>les entreprises de ces territoires.</span></h2><CityLinks slugs={d.near}/><TextLink href="/agences/">Althoce, partout en France</TextLink></div></section>
</main>}
export function NationalPage(){return <main className={b.page}><section className={s.hero}><div className={b.container}><nav className={b.breadcrumb} aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span><span aria-current="page">Althoce en France</span></nav><div className={s.heroGrid}><div><h1>Une IA utile.<br/>Des équipes autonomes.<br/><span>Partout en France.</span></h1><p className={b.lead}>Notre ambition : rendre l’IA accessible aux PME et ETI, avec des usages compris, des données maîtrisées et des solutions adaptées au travail réel.</p><TextLink href="/contact/">Parlons de votre projet</TextLink></div><div className={s.office}><Image src="/images/home/atelier-equipes.webp" alt="Une équipe travaille avec un consultant autour de ses usages et de ses outils" fill priority sizes="(max-width:900px) 90vw, 50vw"/></div></div></div></section><TrustStrip className={b.container}/><section className={b.section}><div className={b.container}><div className={s.heading}><h2>La technologie avance.<br/><span>Votre équipe aussi.</span></h2><p>Nous ne cherchons pas à ajouter de l’IA partout. Nous choisissons avec vous les usages utiles, puis nous donnons aux équipes les moyens de les comprendre et de les faire vivre.</p></div><Offers/></div></section><section className={`${b.section} ${s.soft}`}><div className={`${b.container} ${s.heroGrid}`}><div><h2>La confiance<br/><span>se construit dans le projet.</span></h2><p className={b.lead}>Un périmètre lisible, des sources identifiées, des droits d’accès et des validations humaines. Les choix de modèles et d’hébergement dépendent de vos exigences : ils se discutent avant la mise en œuvre.</p><TextLink href="/services/audit-ia/">Comprendre notre diagnostic IA</TextLink></div><div className={s.office}><Image src="/images/services/construction.webp" alt="Deux collègues examinent ensemble une solution sur leur ordinateur" fill sizes="(max-width:900px) 90vw, 50vw"/></div></div></section><section className={b.section}><div className={b.container}><div className={s.heading}><h2>Bordelais d’origine.<br/><span>À vos côtés en France.</span></h2><p>L’accompagnement se construit autour de votre organisation. Nous définissons les échanges à distance, les ateliers et le suivi selon les besoins de la mission.</p></div><TextLink href="/a-propos/">Rencontrer le cabinet</TextLink></div></section><PreAuditCTA/><CityMarquee cities={cityStories.map(({slug,name})=>({slug,name}))}/></main>}
