import type {Metadata} from 'next';
import Footer from '@/components/Footer';
import {Breadcrumb,PreAuditCTA} from '@/components/brand/Sections';
import GuideLibrary from '@/components/resources/GuideLibrary';
import GuideCarousel from '@/components/resources/GuideCarousel';
import {ResourceCard} from '@/components/resources/ResourceSection';
import {guides,guideUrl,financeGuideSlugs} from '@/lib/resources';
import b from '@/components/brand/Brand.module.css';
import r from '@/components/resources/Resources.module.css';
import s from '@/components/sectors/Sectors.module.css';
const title='Nos guides IA gratuits, par secteur';
const description='Explorez les guides Althoce pour la finance, le droit, le marketing et les données publiques. Des méthodes concrètes pour vos équipes.';
export const metadata:Metadata={title,description,alternates:{canonical:'https://althoce.com/guides/'},openGraph:{title,description,url:'https://althoce.com/guides/',images:[{url:'/og-default.png',width:1200,height:630,alt:'Les guides pratiques IA du cabinet Althoce'}]},twitter:{card:'summary_large_image',title,description,images:['/og-default.png']}};
const groups=[{id:'finance',title:'Finance',text:'Cabinets comptables et directions financières : de la pratique à la transformation du cabinet.',slugs:financeGuideSlugs},{id:'droit',title:'Droit',text:'Des usages pour les avocats et juristes, avec des repères pour encadrer la pratique.',slugs:['claude-droit-10-cas-usage']},{id:'marketing',title:'Marketing & communication',text:'Explorer les analyses de campagne et préparer vos prochaines actions.',slugs:['guide-claude-meta-ads']},{id:'immobilier',title:'Immobilier & données publiques',text:'Des sources à explorer pour contextualiser vos analyses, notamment les valeurs foncières.',slugs:['claude-data-gouv-20-prompts']},{id:'transversal',title:'Tous secteurs : outils & organisation',text:'Des méthodes transversales pour vos équipes, à adapter à votre environnement.',slugs:['copilot-8-cas-usage']}];
export default function Page(){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage',name:title,url:'https://althoce.com/guides/',mainEntity:{'@type':'ItemList',itemListElement:guides.map((g,i)=>({'@type':'ListItem',position:i+1,name:g.title,url:guideUrl(g.slug)}))}}).replace(/</g,'\\u003c')}}/><main className={b.page}><section className={s.hero}><div className={b.container}><Breadcrumb label="Nos guides"/><div className={s.hubIntro}><h1>Des repères pour comprendre.<br/><span>Des guides pour pratiquer.</span></h1><p className={b.lead}>Choisissez votre secteur, découvrez un usage et repartez avec une méthode. Nos guides gratuits sont conçus pour vous aider à faire vos premiers essais avec l’IA.</p></div></div></section><GuideLibrary groups={groups.map(g=>({id:g.id,title:g.title,count:g.slugs.length}))}>{groups.map(group=><section className={b.section} id={group.id} key={group.id} aria-labelledby={`${group.id}-title`}><div className={b.container}><div className={s.heading}><h2 id={`${group.id}-title`}>{group.title}</h2><p>{group.text}</p></div>{group.slugs.length>=4?<GuideCarousel count={group.slugs.length} id={`library-${group.id}`}>{guides.filter(g=>group.slugs.includes(g.slug)).map(g=><ResourceCard key={g.slug} guide={g}/>)}</GuideCarousel>:<div className={`${r.library} ${r.librarySingle}`}>{guides.filter(g=>group.slugs.includes(g.slug)).map(g=><ResourceCard key={g.slug} guide={g}/>)}</div>}</div></section>)}</GuideLibrary><PreAuditCTA title="Et pour votre équipe ?" description="Un guide donne des idées. Un échange permet de les relier à vos outils, vos contraintes et votre quotidien. Parlons-en pendant un premier appel offert."/></main><Footer showCta={false}/></>}
