import TailoredAgents from './TailoredAgents';
import Image from 'next/image';
import { ArrowUpRight, FileCheck2, ChartNoAxesCombined, Landmark, ScanLine, GraduationCap, Database, ArrowRight, FileSpreadsheet, CheckCheck } from 'lucide-react';
import { FaqSection, PreAuditCTA, TextLink } from '@/components/brand/Sections';
import ResourceSection from '@/components/resources/ResourceSection';
import { financeFaq } from '@/lib/resources';
import b from '@/components/brand/Brand.module.css';
import s from './Sectors.module.css';
const audiences=[
 {icon:FileCheck2,title:'Cabinets comptables',text:'Préparer les pièces et la révision. Garder du temps pour expliquer, conseiller et accompagner vos clients.',example:'Du dossier à vérifier au conseil à apporter.'},
 {icon:ChartNoAxesCombined,title:'Directions financières',text:'Rassembler les données, préparer le reporting et faire ressortir les écarts qui méritent votre attention.',example:'Moins de consolidation. Plus de recul.'},
 {icon:ScanLine,title:'Contrôle de gestion',text:'Structurer les analyses et préparer les commentaires, avec des résultats reliés à leurs sources.',example:'Des chiffres à comprendre, pas seulement à produire.'},
 {icon:Landmark,title:'Patrimoine & investissement',text:'Explorer la synthèse de dossiers et la veille documentaire, dans un périmètre défini avec vos équipes.',example:'Une préparation utile. Un jugement qui reste le vôtre.'},
];
export default function FinancePage(){return <main className={b.page}>
 <section className={s.hero}><div className={b.container}><nav className={b.breadcrumb} aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span><a href="/secteurs/">Secteurs</a><span>/</span><span aria-current="page">Finance</span></nav><div className={s.heroGrid}><div><h1>L’IA pour la finance.<br/><span>Plus de place<br/>pour votre analyse.</span></h1><p className={b.lead}>Althoce conçoit des agents IA et des automatisations sur mesure pour vos équipes financières. Connectés à vos logiciels comptables, tableurs et dossiers, ils préparent le travail selon vos règles. Nous formons vos collaborateurs pour leur redonner du temps pour analyser et conseiller.</p><a className={b.primary} href="/contact/">Parlons de vos priorités<ArrowUpRight size={18}/></a><a className={s.secondary} href="#finance-guides-title">Explorer les guides gratuits</a></div><div className={s.heroPhoto}><Image src="/images/sectors/finance-dossiers.webp" alt="Trois collègues échangent autour de dossiers financiers dans un bureau." fill priority sizes="(max-width:900px) 90vw, 48vw"/><div className={s.photoNote}>L’IA prépare.<br/><strong>Votre équipe décide.</strong></div></div></div></div></section>
 <TailoredAgents/>
 <section className={b.section}><div className={b.container}><div className={s.heading}><h2>Le même secteur.<br/><span>Des réalités différentes.</span></h2><p>Une clôture à préparer, un client à conseiller, une décision à éclairer. Nous partons de votre métier pour définir ce qui peut être simplifié.</p></div><div className={s.audiences}>{audiences.map(x=><article key={x.title}><x.icon size={26} strokeWidth={1.5} aria-hidden="true"/><h3>{x.title}</h3><p>{x.text}</p><small>{x.example}</small></article>)}</div></div></section>
 <section className={s.workflow}><div className={b.container}><div className={s.heading}><h2>Vos outils savent déjà beaucoup.<br/><span>Faisons-les travailler ensemble.</span></h2><p>Relier vos données à l’IA pour préparer le travail, sans multiplier les copier-coller.</p></div><div className={s.connection}><div className={s.sourceTools}><span><img src="/logos/pennylane.svg" alt="Pennylane" width={130} height={26}/></span><span><FileSpreadsheet size={22}/>Tableurs & exports</span><span><Database size={22}/>ERP & documents</span></div><ArrowRight className={s.connectionArrow} size={26} aria-hidden="true"/><div className={s.aiCore}><img src="/logos/claude.svg" alt="" width={32} height={32}/><strong>Votre assistant IA</strong><small>Un accès défini.<br/>Des consignes métier.</small></div><ArrowRight className={s.connectionArrow} size={26} aria-hidden="true"/><div className={s.output}><CheckCheck size={26} aria-hidden="true"/><strong>Une analyse à valider</strong><p>Les écarts à examiner, les pièces utiles et une synthèse reliée à ses sources.</p></div></div><p className={s.workflowNote}>Connexion ou export contrôlé : nous choisissons le chemin adapté à vos outils et à vos droits d’accès.</p><div className={s.connectionBenefits}><span><CheckCheck size={17} aria-hidden="true"/>Moins de ressaisies</span><span><CheckCheck size={17} aria-hidden="true"/>Des sources accessibles</span><span><CheckCheck size={17} aria-hidden="true"/>Votre validation à chaque étape</span></div></div></section>

 <section className={b.section}><div className={`${b.container} ${s.training}`}><div className={s.trainingPhoto}><Image src="/images/sectors/finance-formation.webp" alt="Un atelier de formation réunit une petite équipe autour de ses ordinateurs." fill sizes="(max-width:900px) 90vw, 48vw"/></div><div><GraduationCap size={30} strokeWidth={1.5} aria-hidden="true"/><h2>Le progrès se joue<br/><span>aussi dans l’équipe.</span></h2><p className={b.lead}>Un outil n’installe pas une nouvelle habitude à lui seul. Nos formations IA partent de vos dossiers : poser une bonne demande, vérifier une réponse et savoir quelles données utiliser.</p><p className={s.paragraph}>Du dirigeant aux collaborateurs, chacun trouve sa place. Puis nous ajustons les usages et organisons le suivi pour qu’ils restent utiles après le projet.</p><TextLink href="/services/formation-ia/">Découvrir les formations IA</TextLink></div></div></section>
 <section className={b.section}><div className={b.container}><div className={s.heading}><h2>Un reporting à préparer.<br/><span>Un parcours plus court.</span></h2><p>Voici un usage possible pour une direction financière. Le même principe s’adapte aux dossiers d’un cabinet comptable.</p></div><ol className={s.steps}><li><span>01</span><h3>Rassembler les données</h3><p>Récupérer les éléments autorisés depuis les outils connectés, ou charger les exports du mois.</p></li><li><span>02</span><h3>Préparer avec l’IA</h3><p>Faire ressortir les variations et préparer un commentaire accompagné des données qui le justifient.</p></li><li><span>03</span><h3>Vérifier et partager</h3><p>Le responsable financier contrôle les calculs, ajuste l’analyse et diffuse le reporting validé.</p></li></ol><TextLink href="/agent-ia/finance/">Explorer les agents IA sur mesure pour la finance</TextLink></div></section>
 <ResourceSection/>
 <section className={b.section}><div className={b.container}><a href="/cas-clients/cabinet-comptable-lyon/" className={s.case}><div><span>Dans un cabinet comptable lyonnais</span><h2>Accueillir davantage de dossiers.<br/>Garder la relation.</h2><p>La préparation des factures et des rapprochements laisse davantage de place à la vérification et au conseil.</p><strong>Découvrir le cas client <ArrowUpRight size={18} aria-hidden="true"/></strong></div><div className={s.metric}><b>×2</b><p>capacité gérée à effectif constant,<br/>sur quatre mois dans ce cabinet.</p></div></a></div></section>
 <FaqSection id="faq-finance" title="Vos questions, simplement." description="Le point de départ, les outils et la place de votre équipe." items={financeFaq} showContactLink={false}/>
 <PreAuditCTA title={<>Et si vos équipes retrouvaient<br/>le temps d’analyser ?</>}/>
 </main>}
